### Generated by rprotoc. DO NOT EDIT!
### <proto file: lib/odb/object_format.proto>
# package Odb;
# 
# message ObjectFormat {
#   enum ObjectType {
#     PRIMITIVE   = 0;
#     USER_OBJECT = 1;
#     COLLECTION  = 2;
#   }
#   
#   message UserObject {
#     message InstanceVariable {
#       required string name          = 1;
#       required int32  object_id     = 2;
#     }
# 
#     required string           class_name         = 1;
#     repeated InstanceVariable instance_variables = 2;
#   }
#   
#   required int32      id              = 1;
#   required ObjectType object_type     = 2;
#   required int32      data_length     = 3;
#   required string     data            = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Odb
  class ObjectFormat < ::Protobuf::Message
    defined_in __FILE__
    class ObjectType < ::Protobuf::Enum
      defined_in __FILE__
      PRIMITIVE = 0
      USER_OBJECT = 1
      COLLECTION = 2
    end
    class UserObject < ::Protobuf::Message
      defined_in __FILE__
      class InstanceVariable < ::Protobuf::Message
        defined_in __FILE__
        required :string, :name, 1
        required :int32, :object_id, 2
      end
      required :string, :class_name, 1
      repeated :InstanceVariable, :instance_variables, 2
    end
    required :int32, :id, 1
    required :ObjectType, :object_type, 2
    required :int32, :data_length, 3
    required :string, :data, 4
  end
end