### Generated by rprotoc. DO NOT EDIT!
### <proto file: lib/odb/object_format.proto>
# package Odb;
# 
# message ObjectFormat {
#   message Primitive {
#     enum Primitives {
#       NIL   = 0;
#       FALSE = 1;
#       TRUE  = 2;
#     }
#   
#     required Primitives primitive = 1;
#   }
#   
#   message UserDefinedObject {
#     message InstanceVariable {
#       required string name      = 1;
#       required int32  object_id = 2;
#     }
#   
#     required string           class_name = 1;
#     repeated InstanceVariable ivars      = 2  [packed = true];
#   }
#   
#   required int32             object_id = 1;
#   optional Primitive         primitive = 2;
#   optional UserDefinedObject data      = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Odb
  class ObjectFormat < ::Protobuf::Message
    defined_in __FILE__
    class Primitive < ::Protobuf::Message
      defined_in __FILE__
      class Primitives < ::Protobuf::Enum
        defined_in __FILE__
        NIL = 0
        FALSE = 1
        TRUE = 2
      end
      required :Primitives, :primitive, 1
    end
    class UserDefinedObject < ::Protobuf::Message
      defined_in __FILE__
      class InstanceVariable < ::Protobuf::Message
        defined_in __FILE__
        required :string, :name, 1
        required :int32, :object_id, 2
      end
      required :string, :class_name, 1
      repeated :InstanceVariable, :ivars, 2, :packed => true
    end
    required :int32, :object_id, 1
    optional :Primitive, :primitive, 2
    optional :UserDefinedObject, :data, 3
  end
end